name: Build Android APK
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build web app
        run: npm run build
      
      - name: Sync Capacitor
        run: npx cap sync android
      
      - name: Setup Gradle Wrapper
        run: |
          mkdir -p android/gradle/wrapper
          curl -L https://raw.githubusercontent.com/gradle/gradle/master/gradle/wrapper/gradle-wrapper.jar -o android/gradle/wrapper/gradle-wrapper.jar
          curl -L https://raw.githubusercontent.com/gradle/gradle/master/gradlew -o android/gradlew
          curl -L https://raw.githubusercontent.com/gradle/gradle/master/gradlew.bat -o android/gradlew.bat
          cat > android/gradle/wrapper/gradle-wrapper.properties << 'EOF'
          distributionBase=GRADLE_USER_HOME
          distributionPath=wrapper/dists
          distributionUrl=https\://services.gradle.org/distributions/gradle-8.9-bin.zip
          networkTimeout=10000
          validateDistributionUrl=true
          zipStoreBase=GRADLE_USER_HOME
          zipStorePath=wrapper/dists
          EOF
          chmod +x android/gradlew
      
      - name: Build Debug APK
        run: cd android && ./gradlew assembleDebug
      
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: mate-search-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30
      
      - name: Build Release APK (unsigned)
        id: release
        run: cd android && ./gradlew assembleRelease
        continue-on-error: true
      
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        if: steps.release.outcome == 'success'
        with:
          name: mate-search-release
          path: android/app/build/outputs/apk/release/app-release-unsigned.apk
          retention-days: 30
